name: heroku

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "planninge3qrf3rar232rr4444r4r" #Must be unique in Heroku
          heroku_email: "m.a.solano93@gmail.com"
          healthcheck: "https://[YOUR APP's NAME].herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
